### ISSUE TITLE
Error with 'package mediapipe': additional text appended after `arch`, 'source' and 'md5' section

### ISSUE THREAD

**Issue by fengwang** [anntzer/pypi2pkgbuild#19]
I noticed there is some additional version info attached to `arch`, 'source' and 'md5' section in the PKGBUILD, for example:
`source_2_17_x86_64.manylinux2014_x86_64=(https://files.pythonhosted.org/packages/7a/69/63758cb8cdb62da9a1d9f67fd10ca103047c804560aba0d3e259ead4c92a/mediapipe-0.8.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)`

The output of `pypi2pkgbuild.py -v mediapipe`:
```
DEBUG:pypi2pkgbuild:This is pypi2pkgbuild 0.2.post44+g1b62cfa.
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile pkgfile >/dev/null
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/mediapipe-*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
DEBUG:pypi2pkgbuild:Running subprocess:
pacman -Q python-mediapipe 2>/dev/null
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/mediapipe-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/mediapipe-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-mediapipe 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
INFO:pypi2pkgbuild:Packaging python-mediapipe 0.8.4.2.
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/pip-*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/pip-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-pip 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
DEBUG:pypi2pkgbuild:Running subprocess from /tmp/tmp4n7yd63r:
makepkg --printsrcinfo | grep -Po '(?<=^\tmakedepends = ).*'
DEBUG:pypi2pkgbuild:Running subprocess:
pacman -Q python-pip >/dev/null 2>&1
DEBUG:pypi2pkgbuild:Running subprocess from /tmp/tmp8i1d5amn:
makepkg
DEBUG:pypi2pkgbuild:Running subprocess:

set -e
python -mvenv /tmp/tmpueswz2t7
# Leave the source directory, which may contain wheels/sdists/etc.
cd /tmp/tmpueswz2t7
. '/tmp/tmpueswz2t7/bin/activate'
pip install --upgrade pip >/dev/null
install_cmd() {
    pip list --format=freeze | cut -d= -f1 | sort >'/tmp/tmpueswz2t7/pre'
    if ! pip install --no-deps 'mediapipe==0.8.4.2.*,<0.8.4.2.1'; then
        return 1
    fi
    pip list --format=freeze | cut -d= -f1 | sort >'/tmp/tmpueswz2t7/post'
    # installed name, or real name if it doesn't appear
    # (setuptools, pip, Cython, numpy).
    install_name="$(comm -13 '/tmp/tmpueswz2t7/pre' '/tmp/tmpueswz2t7/post')"
    # the requirement can be 'req_name==version', or a path name.
    if [[ -z "$install_name" ]]; then
        if [[ -e 'mediapipe==0.8.4.2.*,<0.8.4.2.1' ]]; then
            install_name="$(basename 'mediapipe==0.8.4.2.*,<0.8.4.2.1' .git)"
        else
            install_name="$(echo 'mediapipe==0.8.4.2.*,<0.8.4.2.1' | cut -d= -f1 -)"
        fi
    fi
}
show_cmd() {
    python - "$(pip show -v "$install_name")" <<EOF
from email.parser import Parser
import json
import sys
print(json.dumps(dict(Parser().parsestr(sys.argv[1]))))
EOF
}
if install_cmd >/tmp/tmp67a9cqu5; then
    show_cmd
else
    pip install numpy >/dev/null
    echo numpy >>/tmp/tmpcsftb3ch
    install_cmd >/tmp/tmp67a9cqu5
    show_cmd
fi

DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/absl_py-*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/absl_py-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l absl-py 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/protobuf-*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/protobuf-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-protobuf 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/six-*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/six-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-six 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/attrs-*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/attrs-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-attrs 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/numpy-*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/numpy-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-numpy 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/opencv_contrib_python-*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/opencv_contrib_python-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/opencv_contrib_python-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-opencv-contrib-python 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/wheel-*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/wheel-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-wheel 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/mediapipe-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/mediapipe-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pip download --no-deps -d /tmp/tmp4nf544lt 'mediapipe==0.8.4.2.*,<0.8.4.2.1'
Collecting mediapipe<0.8.4.2.1,==0.8.4.2.*
  Using cached mediapipe-0.8.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.1 MB)
Saved /tmp/tmp4nf544lt/mediapipe-0.8.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Successfully downloaded mediapipe
DEBUG:pypi2pkgbuild:Running subprocess from python-mediapipe:
makepkg --cleanbuild --nodeps
/home/feng/tmp/program/python/python-mediapipe/tmp/python-mediapipe/PKGBUILD: line 23: syntax error near unexpected token `https://files.pythonhosted.org/packages/7a/69/63758cb8cdb62da9a1d9f67fd10ca103047c804560aba0d3e259ead4c92a/mediapipe-0.8.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'
/home/feng/tmp/program/python/python-mediapipe/tmp/python-mediapipe/PKGBUILD: line 23: `source_2_17_x86_64.manylinux2014_x86_64=(https://files.pythonhosted.org/packages/7a/69/63758cb8cdb62da9a1d9f67fd10ca103047c804560aba0d3e259ead4c92a/mediapipe-0.8.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)'
==> ERROR: Failed to source /home/feng/tmp/program/python/python-mediapipe/tmp/python-mediapipe/PKGBUILD
Traceback (most recent call last):
  File "/usr/bin/pypi2pkgbuild.py", line 1552, in <module>
    sys.exit(main())
  File "/usr/bin/pypi2pkgbuild.py", line 1529, in main
    create_package(name, Options(**vars(args), is_dep=False))
  File "/usr/bin/pypi2pkgbuild.py", line 1325, in create_package
    pkg.write_to(options)
  File "/usr/bin/pypi2pkgbuild.py", line 864, in write_to
    _run_shell(cmd, cwd=cwd)
  File "/usr/bin/pypi2pkgbuild.py", line 322, in _run_shell
    cproc = subprocess.run(args, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['makepkg', '--cleanbuild', '--nodeps']' returned non-zero exit status 6.
```

The Generated PKGBUILD file:
```
# Maintainer: Unknown Packager

export PIP_CONFIG_FILE=/dev/null
export PIP_DISABLE_PIP_VERSION_CHECK=true

pkgname=python-mediapipe
epoch=
pkgver=0.8.4.2
pkgrel=00
pkgdesc='MediaPipe is the simplest way for researchers and developers to build world-class ML solutions and applications for mobile, edge, cloud and the web.'
arch=(2_17_x86_64.manylinux2014_x86_64)
url=https://github.com/google/mediapipe
license=(Apache)
depends=(python absl-py python-protobuf python-six python-attrs python-numpy python-opencv-contrib-python python-wheel)
## EXTRA_DEPENDS ##
makedepends=(python-pip)
checkdepends=()
provides=()
conflicts=(${provides%=*})  # No quotes, to avoid an empty entry.
source=(PKGBUILD_EXTRAS)
md5sums=(SKIP)
noextract=()
source_2_17_x86_64.manylinux2014_x86_64=(https://files.pythonhosted.org/packages/7a/69/63758cb8cdb62da9a1d9f67fd10ca103047c804560aba0d3e259ead4c92a/mediapipe-0.8.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
md5sums_2_17_x86_64.manylinux2014_x86_64=(5130173b94ffc238c982641113c0746b)
noextract+=(mediapipe-0.8.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
source+=(LICENSE)
md5sums+=(86d3f3a95c324c9479bd8986968f4327)

_first_source() {
    echo " ${source_i686[@]} ${source_x86_64[@]} ${source[@]}" |
        tr ' ' '\n' | grep -Pv '^(PKGBUILD_EXTRAS)?$' | head -1
}

_vcs="$(grep -Po '^[a-z]+(?=\+)' <<< "$(_first_source)")"
if [[ "$_vcs" ]]; then
    makedepends+=("$(pkgfile --quiet /usr/bin/$_vcs)")
    provides+=("${pkgname%-$_vcs}")
    conflicts+=("${pkgname%-$_vcs}")
fi

_is_wheel() {
    [[ $(_first_source) =~ \.whl$ ]]
}

if [[ _is_wheel &&
      $(basename "$(_first_source)" | rev | cut -d- -f1 | rev) =~ ^manylinux ]]; then
    options=(!strip)  # https://github.com/pypa/manylinux/issues/119
fi

_dist_name() {
    find "$srcdir" -mindepth 1 -maxdepth 1 -type d -printf '%f
' |
        grep -v '^_tmpenv$'
}

if [[ $(_first_source) =~ ^git+ ]]; then
    _pkgver() {
        ( set -o pipefail
          cd "$srcdir/$(_dist_name)"
          git describe --long --tags 2>/dev/null |
            sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g' ||
          printf "r%s.%s" \
              "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
        )
    }

    pkgver() { _pkgver; }
fi

_build() {
    if _is_wheel; then return; fi
    cd "$srcdir"
    # See Arch Wiki/PKGBUILD/license.
    # Get the first filename that matches.
    local test_name
    if [[ ${license[0]} =~ ^(BSD|MIT|ZLIB|Python)$ ]]; then
        for test_name in LICENSE LICENSE.txt license.txt COPYING COPYING.md COPYING.rst COPYING.txt COPYRIGHT; do
            if cp "$srcdir/$(_dist_name)/$test_name" "$srcdir/LICENSE" 2>/dev/null; then
                break
            fi
        done
    fi
    # Use the latest version of pip, as Arch's version is historically out of
    # date(!) and newer versions do fix bugs (sometimes).
    python -mvenv --clear --system-site-packages _tmpenv
    _tmpenv/bin/pip --quiet install -U pip
    # Build the wheel (which we allow to fail) only after fetching the license.
    # In order to isolate from ~/.pydistutils.cfg, we need to set $HOME to a
    # temporary directory, and thus first $XDG_CACHE_HOME back to its real
    # location, so that pip inserts the wheel in the wheel cache.  We cannot
    # use --global-option=--no-user-cfg instead because that fully disables
    # wheels, causing a from-source build of build dependencies such as
    # numpy/scipy.
    XDG_CACHE_HOME="${XDG_CACHE_HOME:-"$HOME/.cache"}" HOME=_tmpenv \
        _tmpenv/bin/pip wheel -v --no-deps --wheel-dir="$srcdir" \
        "./$(_dist_name)" || true
}

build() { _build; }

_check() {
    # Define check(), possibly using _check as a helper, to run the tests.
    # You may need to call `python setup.py build_ext -i` first.
    if _is_wheel; then return; fi
    cd "$srcdir/$(_dist_name)"
    /usr/bin/python setup.py -q test
}

_package() {
    cd "$srcdir"
    # pypa/pip#3063: pip always checks for a globally installed version.
    python -mvenv --clear --system-site-packages _tmpenv
    _tmpenv/bin/pip install --prefix="$pkgdir/usr" \
        --no-deps --ignore-installed --no-warn-script-location \
        "$(ls ./*.whl 2>/dev/null || echo ./"$(_dist_name)")"
    if [[ -d "$pkgdir/usr/bin" ]]; then  # Fix entry points.
        for f in "$pkgdir/usr/bin/"*; do
            if [[ $(head -n1 "$f") = "#!$(readlink -f _tmpenv)/bin/python" ]]; then
                sed -i '1c#!/usr/bin/python' "$f"
            fi
        done
    fi
    if [[ -d "$pkgdir/usr/etc" ]]; then
        mv "$pkgdir/usr/etc" "$pkgdir/etc"
    fi
    if [[ -f LICENSE ]]; then
        install -D -m644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
    fi
}

package() { _package; }

. "$(dirname "$BASH_SOURCE")/PKGBUILD_EXTRAS"

# Remove makedepends already in depends (which may have been listed for the
# first build, but autodetected on the second.
makedepends=($(printf '%s\n' "${makedepends[@]}" |
               grep -Pwv "^($(IFS='|'; echo "${depends[*]}"))$"))
:  # Apparently ending with makedepends assignment sometimes fails.

```

**Comment by anntzer** [comment]
I think this should be fixed as of master, can you try?

**Comment by fengwang** [comment]
I will do it tomorrow . Thx for the quick reply.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fengwang** [comment]
> I think this should be fixed as of master, can you try?

I confirm this has been fixed in the git version.
