### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by Farzat07** [anntzer/pypi2pkgbuild#20]
With dash as /bin/sh, the output of ```pypi2pkgbuild.py -v tg-archive``` is:
```
DEBUG:pypi2pkgbuild:This is pypi2pkgbuild 0.3.post1+g0c906f8.
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile pkgfile >/dev/null
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/tg_archive[.-]*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
/bin/sh: 1: shopt: not found
DEBUG:pypi2pkgbuild:Running subprocess:
pacman -Q python-tg-archive 2>/dev/null
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/tg_archive-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/tg_archive-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-tg-archive 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
INFO:pypi2pkgbuild:Packaging python-tg-archive 0.3.10.
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/pip[.-]*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
/bin/sh: 1: shopt: not found
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/pip-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-pip 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/wheel[.-]*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
/bin/sh: 1: shopt: not found
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/wheel-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-wheel 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
DEBUG:pypi2pkgbuild:Running subprocess:
pip download --no-deps -d /tmp/tmph_oguzgz --no-binary=tg-archive 'tg-archive==0.3.10.*,<0.3.10.1'
WARNING: Keyring is skipped due to an exception: Failed to open keyring: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6.
Collecting tg-archive<0.3.10.1,==0.3.10.*
  Using cached tg-archive-0.3.10.tar.gz (88 kB)
Saved /tmp/tmph_oguzgz/tg-archive-0.3.10.tar.gz
Successfully downloaded tg-archive
DEBUG:pypi2pkgbuild:Running subprocess from /tmp/tmpqdxwvb1s:
makepkg --printsrcinfo | grep -Po '(?<=^\tmakedepends = ).*'
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pacman -Q python-pip >/dev/null 2>&1
DEBUG:pypi2pkgbuild:Running subprocess:
pacman -Q python-wheel >/dev/null 2>&1
DEBUG:pypi2pkgbuild:Running subprocess from /tmp/tmpsh4ckb9e:
makepkg
DEBUG:pypi2pkgbuild:Running subprocess:

set -e
python -mvenv /tmp/tmpfundzan_
# Leave the source directory, which may contain wheels/sdists/etc.
cd /tmp/tmpfundzan_
. '/tmp/tmpfundzan_/bin/activate'
pip install --upgrade pip wheel >/dev/null
install_cmd() {
    pip list --format=freeze | cut -d= -f1 | sort >'/tmp/tmpfundzan_/pre'
    if ! pip install --no-deps 'tg-archive==0.3.10.*,<0.3.10.1'; then
        return 1
    fi
    pip list --format=freeze | cut -d= -f1 | sort >'/tmp/tmpfundzan_/post'
    # installed name, or real name if it doesn't appear
    # (setuptools, pip, Cython, numpy).
    install_name="$(comm -13 '/tmp/tmpfundzan_/pre' '/tmp/tmpfundzan_/post')"
    # the requirement can be 'req_name==version', or a path name.
    if [[ -z "$install_name" ]]; then
        if [[ -e 'tg-archive==0.3.10.*,<0.3.10.1' ]]; then
            install_name="$(basename 'tg-archive==0.3.10.*,<0.3.10.1' .git)"
        else
            install_name="$(echo 'tg-archive==0.3.10.*,<0.3.10.1' | cut -d= -f1 -)"
        fi
    fi
}
show_cmd() {
    python - "$(pip show -v "$install_name")" <<EOF
from email.parser import Parser
import json
import sys
print(json.dumps(dict(Parser().parsestr(sys.argv[1]))))
EOF
}
if install_cmd >/tmp/tmpxq_r4ups; then
    show_cmd
else
    pip install numpy >/dev/null
    echo numpy >>/tmp/tmp9orrn10i
    install_cmd >/tmp/tmpxq_r4ups
    show_cmd
fi

  ERROR: Command errored out with exit status 1:
   command: /tmp/tmpfundzan_/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_hek9der/tg-archive_f85f69e6a56d47d8bf2fe4019755bbb6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_hek9der/tg-archive_f85f69e6a56d47d8bf2fe4019755bbb6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-76v9ysek
       cwd: /tmp/pip-install-_hek9der/tg-archive_f85f69e6a56d47d8bf2fe4019755bbb6/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-_hek9der/tg-archive_f85f69e6a56d47d8bf2fe4019755bbb6/setup.py", line 5, in <module>
      from tgarchive import __version__
    File "/tmp/pip-install-_hek9der/tg-archive_f85f69e6a56d47d8bf2fe4019755bbb6/tgarchive/__init__.py", line 6, in <module>
      import yaml
  ModuleNotFoundError: No module named 'yaml'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/90/54/2f0c5ec169ebfe0ab1c68c2b960acac248ab8b6b9ed6614208d484bed5b6/tg-archive-0.3.10.tar.gz#sha256=9907a70640977083fe5125e5c341c36db5fce4f7325aa163ac9e0be8b5916c1c (from https://pypi.org/simple/tg-archive/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tg-archive<0.3.10.1,==0.3.10.* (from versions: 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10)
ERROR: No matching distribution found for tg-archive<0.3.10.1,==0.3.10.*
  ERROR: Command errored out with exit status 1:
   command: /tmp/tmpfundzan_/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_n83y9yg/tg-archive_79aef59430494c3e94170a8513305e26/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_n83y9yg/tg-archive_79aef59430494c3e94170a8513305e26/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w7laywqi
       cwd: /tmp/pip-install-_n83y9yg/tg-archive_79aef59430494c3e94170a8513305e26/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-_n83y9yg/tg-archive_79aef59430494c3e94170a8513305e26/setup.py", line 5, in <module>
      from tgarchive import __version__
    File "/tmp/pip-install-_n83y9yg/tg-archive_79aef59430494c3e94170a8513305e26/tgarchive/__init__.py", line 6, in <module>
      import yaml
  ModuleNotFoundError: No module named 'yaml'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/90/54/2f0c5ec169ebfe0ab1c68c2b960acac248ab8b6b9ed6614208d484bed5b6/tg-archive-0.3.10.tar.gz#sha256=9907a70640977083fe5125e5c341c36db5fce4f7325aa163ac9e0be8b5916c1c (from https://pypi.org/simple/tg-archive/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tg-archive<0.3.10.1,==0.3.10.* (from versions: 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10)
ERROR: No matching distribution found for tg-archive<0.3.10.1,==0.3.10.*
Collecting tg-archive<0.3.10.1,==0.3.10.*
  Using cached tg-archive-0.3.10.tar.gz (88 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
ERROR:pypi2pkgbuild:Failed to obtain metadata for tg-archive==0.3.10.*,<0.3.10.1.
```

With bash as /bin/sh, the output of ```pypi2pkgbuild.py -v tg-archive``` is:
```
DEBUG:pypi2pkgbuild:This is pypi2pkgbuild 0.3.post1+g0c906f8.
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile pkgfile >/dev/null
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/tg_archive[.-]*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pacman -Q python-tg-archive 2>/dev/null
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/tg_archive-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/tg_archive-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-tg-archive 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
INFO:pypi2pkgbuild:Packaging python-tg-archive 0.3.10.
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/pip[.-]*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/pip-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-pip 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
(shopt -s nocaseglob; pacman -Qo /usr/lib/python3.9/site-packages/wheel[.-]*-info 2>/dev/null) | rev | cut -d' ' -f1,2 | rev
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -riv '^/usr/lib/python3\.9/site-packages/wheel-.*py3\.9\.egg-info' | cut -f1 | uniq | cut -d/ -f2
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile -l python-wheel 2>/dev/null | grep -Po '(?<=site-packages/)[^-/]*(?=.*\.egg-info/?$)'
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pip download --no-deps -d /tmp/tmp66nhadde --no-binary=tg-archive 'tg-archive==0.3.10.*,<0.3.10.1'
WARNING: Keyring is skipped due to an exception: Failed to open keyring: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.kde.kwalletd5 received signal 6.
Collecting tg-archive<0.3.10.1,==0.3.10.*
  Using cached tg-archive-0.3.10.tar.gz (88 kB)
Saved /tmp/tmp66nhadde/tg-archive-0.3.10.tar.gz
Successfully downloaded tg-archive
DEBUG:pypi2pkgbuild:Running subprocess from /tmp/tmp1zt2p06a:
makepkg --printsrcinfo | grep -Po '(?<=^\tmakedepends = ).*'
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pacman -Q python-pip >/dev/null 2>&1
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess:
pacman -Q python-wheel >/dev/null 2>&1
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
DEBUG:pypi2pkgbuild:Running subprocess from /tmp/tmpe_nob2vs:
makepkg
DEBUG:pypi2pkgbuild:Running subprocess:

set -e
python -mvenv /tmp/tmpdnbn59x2
# Leave the source directory, which may contain wheels/sdists/etc.
cd /tmp/tmpdnbn59x2
. '/tmp/tmpdnbn59x2/bin/activate'
pip install --upgrade pip wheel >/dev/null
install_cmd() {
    pip list --format=freeze | cut -d= -f1 | sort >'/tmp/tmpdnbn59x2/pre'
    if ! pip install --no-deps 'tg-archive==0.3.10.*,<0.3.10.1'; then
        return 1
    fi
    pip list --format=freeze | cut -d= -f1 | sort >'/tmp/tmpdnbn59x2/post'
    # installed name, or real name if it doesn't appear
    # (setuptools, pip, Cython, numpy).
    install_name="$(comm -13 '/tmp/tmpdnbn59x2/pre' '/tmp/tmpdnbn59x2/post')"
    # the requirement can be 'req_name==version', or a path name.
    if [[ -z "$install_name" ]]; then
        if [[ -e 'tg-archive==0.3.10.*,<0.3.10.1' ]]; then
            install_name="$(basename 'tg-archive==0.3.10.*,<0.3.10.1' .git)"
        else
            install_name="$(echo 'tg-archive==0.3.10.*,<0.3.10.1' | cut -d= -f1 -)"
        fi
    fi
}
show_cmd() {
    python - "$(pip show -v "$install_name")" <<EOF
from email.parser import Parser
import json
import sys
print(json.dumps(dict(Parser().parsestr(sys.argv[1]))))
EOF
}
if install_cmd >/tmp/tmp9vsocvxb; then
    show_cmd
else
    pip install numpy >/dev/null
    echo numpy >>/tmp/tmpg9z8ony0
    install_cmd >/tmp/tmp9vsocvxb
    show_cmd
fi

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
  ERROR: Command errored out with exit status 1:
   command: /tmp/tmpdnbn59x2/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uf20to9i/tg-archive_5709bf1706544a8193664f5d75ccaf2e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uf20to9i/tg-archive_5709bf1706544a8193664f5d75ccaf2e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-02m9q46v
       cwd: /tmp/pip-install-uf20to9i/tg-archive_5709bf1706544a8193664f5d75ccaf2e/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-uf20to9i/tg-archive_5709bf1706544a8193664f5d75ccaf2e/setup.py", line 5, in <module>
      from tgarchive import __version__
    File "/tmp/pip-install-uf20to9i/tg-archive_5709bf1706544a8193664f5d75ccaf2e/tgarchive/__init__.py", line 6, in <module>
      import yaml
  ModuleNotFoundError: No module named 'yaml'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/90/54/2f0c5ec169ebfe0ab1c68c2b960acac248ab8b6b9ed6614208d484bed5b6/tg-archive-0.3.10.tar.gz#sha256=9907a70640977083fe5125e5c341c36db5fce4f7325aa163ac9e0be8b5916c1c (from https://pypi.org/simple/tg-archive/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tg-archive<0.3.10.1,==0.3.10.* (from versions: 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10)
ERROR: No matching distribution found for tg-archive<0.3.10.1,==0.3.10.*
  ERROR: Command errored out with exit status 1:
   command: /tmp/tmpdnbn59x2/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uug1ah19/tg-archive_0d2d045b3bde42e7baccd01218c95fba/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uug1ah19/tg-archive_0d2d045b3bde42e7baccd01218c95fba/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tnkx194q
       cwd: /tmp/pip-install-uug1ah19/tg-archive_0d2d045b3bde42e7baccd01218c95fba/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-uug1ah19/tg-archive_0d2d045b3bde42e7baccd01218c95fba/setup.py", line 5, in <module>
      from tgarchive import __version__
    File "/tmp/pip-install-uug1ah19/tg-archive_0d2d045b3bde42e7baccd01218c95fba/tgarchive/__init__.py", line 6, in <module>
      import yaml
  ModuleNotFoundError: No module named 'yaml'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/90/54/2f0c5ec169ebfe0ab1c68c2b960acac248ab8b6b9ed6614208d484bed5b6/tg-archive-0.3.10.tar.gz#sha256=9907a70640977083fe5125e5c341c36db5fce4f7325aa163ac9e0be8b5916c1c (from https://pypi.org/simple/tg-archive/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tg-archive<0.3.10.1,==0.3.10.* (from versions: 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10)
ERROR: No matching distribution found for tg-archive<0.3.10.1,==0.3.10.*
Collecting tg-archive<0.3.10.1,==0.3.10.*
  Using cached tg-archive-0.3.10.tar.gz (88 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
ERROR:pypi2pkgbuild:Failed to obtain metadata for tg-archive==0.3.10.*,<0.3.10.1.
```

**Comment by anntzer** [comment]
This is a bug on tg-archive's side, which cannot be installed without yaml present first.  You can use `--setup-requires` to workaround that, though.
