### ISSUE TITLE
Virtualenv failes to find namcap

### ISSUE THREAD

**Issue by alan1world** [anntzer/pypi2pkgbuild#30]
Building a package in a virtualenv fails to find namcap in Arch Linux.
namcap is installed on the host

The package itself seems  to build; it fails on namcap after.

```
==> Finished making: python-syrupy 3.0.4-00 (Fri 04 Nov 2022 02:06:19 PM GMT)
DEBUG:pypi2pkgbuild:Running subprocess from python-syrupy:
makepkg --packagelist
DEBUG:pypi2pkgbuild:Running subprocess from python-syrupy:
namcap /home/user/vnev/pypi2pkgbuild/python-syrupy/python-syrupy-3.0.4-00-any.pkg.tar.zst
/home/user/vnev/pypi2pkgbuild/bin/python3: No module named namcap
Traceback (most recent call last):
  File "/home/user/vnev/pypi2pkgbuild/bin/pypi2pkgbuild.py", line 1555, in <module>
    sys.exit(main())
  File "/home/user/vnev/pypi2pkgbuild/bin/pypi2pkgbuild.py", line 1532, in main
    create_package(name, Options(**vars(args), is_dep=False))
  File "/home/user/vnev/pypi2pkgbuild/bin/pypi2pkgbuild.py", line 1327, in create_package
    pkg.write_to(options)
  File "/home/user/vnev/pypi2pkgbuild/bin/pypi2pkgbuild.py", line 876, in write_to
    namcap = (_run_shell(["namcap", fullpath], cwd=cwd, stdout=PIPE)
  File "/home/user/vnev/pypi2pkgbuild/bin/pypi2pkgbuild.py", line 322, in _run_shell
    cproc = subprocess.run(args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['namcap', PosixPath('/home/user/vnev/pypi2pkgbuild/python-syrupy/python-syrupy-3.0.4-00-any.pkg.tar.zst')]' returned non-zero exit status 1.

```

**Comment by alan1world** [comment]
NB: It works fine if I install to the host system (using https://aur.archlinux.org/packages/python-pypi2pkgbuild) and then attempt the build in a temp dir.

It only fails when run inside a venv.

**Comment by anntzer** [comment]
I consider this to be a bug in namcap, see https://bugs.archlinux.org/task/59844. I don't really want to spend time arguing with the maintainers, but perhaps you can have a go...
