### ISSUE TITLE
python2 support?

### ISSUE THREAD

**Issue by hrehfeld** [anntzer/pypi2pkgbuild#9]
I'm trying to use the tool for a python2 pkg (https://github.com/chrisspen/freekey), but it chokes on obvious 2 vs 3 errors.

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-u5bigqmg-build/
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-rfc2le3n-build/
Processing /tmp/tmp7rajvas4/freekey-git
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-rfc2le3n-build/setup.py", line 17
        print 'writing %s' % bin_dst_fqfn
                         ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'writing %s' % bin_dst_fqfn)?
    
    ----------------------------------------
```

**Comment by anntzer** [comment]
There is no support for creating Py2 packages, and I will not consider adding such support.
I clarified the README accordingly.
